apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-1h
spec:
  schedule: "5 * * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1800
      template:
        spec:
          volumes:
          - name: usercert
            secret:
              secretName: "{{ .Values.cronjobSettings.daemonName }}-fts-cert"
          - name: userkey
            secret:
              secretName: "{{ .Values.cronjobSettings.daemonName }}-fts-key"
          {{- range $key, $val := .Values.persistentVolumes }}
          - name: {{ $key }}
            persistentVolumeClaim:
              claimName: {{ $val.name }}
          {{- end}}
          containers:
            - name: {{ .Release.Name }}-1h
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              volumeMounts:
                - name: usercert
                  mountPath: /opt/rucio/certs/
                - name: userkey
                  mountPath: /opt/rucio/keys/
                {{- range $key, $val := .Values.persistentVolumes }}
                - name: {{ $key }}
                  mountPath: {{ $val.mountPath }}
                {{- end}}
              env:
                - name: RUCIO_HOME
                  value: "/opt/rucio-{{ .Values.cronjobSettings.instance }}"
                - name: TEST_SUFFIX
                  value: "{{ .Values.cronjobSettings.instance }}"
                - name: GITLAB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: "rucio-secrets"
                      key: gitlab_token
                - name: MONIT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: "rucio-secrets"
                      key: monit_token
              command: ['/root/CMSRucio/docker/CMSRucioClient/scripts/k8s_sync_sites.sh']
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-12h
spec:
  schedule: "10 */12 * * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 7200
      template:
        spec:
          volumes:
          - name: usercert
            secret:
              secretName: "{{ .Values.cronjobSettings.daemonName }}-fts-cert"
          - name: userkey
            secret:
              secretName: "{{ .Values.cronjobSettings.daemonName }}-fts-key"
          {{- range $key, $val := .Values.persistentVolumes }}
          - name: {{ $key }}
            persistentVolumeClaim:
              claimName: {{ $val.name }}
          {{- end}}
          containers:
            - name: {{ .Release.Name }}-12h
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              volumeMounts:
                - name: usercert
                  mountPath: /opt/rucio/certs/
                - name: userkey
                  mountPath: /opt/rucio/keys/
                {{- range $key, $val := .Values.persistentVolumes }}
                - name: {{ $key }}
                  mountPath: {{ $val.mountPath }}
                {{- end}}
              env:
                - name: RUCIO_HOME
                  value: "/opt/rucio-{{ .Values.cronjobSettings.instance }}"
                - name: TEST_SUFFIX
                  value: "{{ .Values.cronjobSettings.instance }}"
                - name: GITLAB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: "rucio-secrets"
                      key: gitlab_token
                - name: MONIT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: "rucio-secrets"
                      key: monit_token
                - name: IAM_SERVER
                  value: "{{ .Values.oidc.iamServer }}"
                - name: IAM_CLIENT_ID
                  value: "{{ .Values.oidc.iamClientId }}"
                - name: IAM_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: "rucio-secrets"
                      key: oidc_iam_client_secret
                      optional: true
                - name: REFRESH_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: "rucio-secrets"
                      key: oidc_iam_refresh_token
                      optional: true
              command: ['/root/CMSRucio/docker/CMSRucioClient/scripts/k8s_sync_users_links.sh']
          restartPolicy: OnFailure
